image: maven:3-jdk-11

# before_script : 
#   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
#   - eval $(ssh-agent -s)
#   - echo $SSH_PRIVATE_KEY | tr -d '\r' | ssh-add -
#   - mkdir -p ~/.ssh
#   - chmod 700 ~/.ssh
#   - ssh fmh@130.193.44.96

variables:
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build-job:
  script:
      - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
      - eval $(ssh-agent -s)
      - echo $SSH_PRIVATE_KEY | tr -d '\r'
      - echo $SSH_PRIVATE_KEY | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - ssh fmh@130.193.44.96
#   image: docker:19.03.12
#   stage: build
#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   script:
#     - docker build --pull -t $CONTAINER_TEST_IMAGE .
#     - docker push $CONTAINER_TEST_IMAGE

# test-job:
#   stage: test
#   services:
#     - docker:dind
#   script:
#     - mvn test -P test

# deploy-prod:
#   image: docker:19.03.12
#   stage: deploy
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#     - docker push $CONTAINER_RELEASE_IMAGE
#   only:
#     - develop
