build-job:
  stage: build-dev
  script:
    - mvn clean install -P dev

test-job:
  stage: build-test
  script:
    - mvn clean install -P test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
