spring:
  datasource:
    url: jdbc:tc:postgresql:9.6:///

#    url: jdbc:tc:postgresql:9.6:///?TC_INITSCRIPT=file:src/main/resources/db/migration/V2__data_initialisation.sql
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  flyway:
    baseline-on-migrate: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect