
spring:
#  profiles: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/FMH_DB
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    platform: postgres
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        format_sql: true
#---
#spring:
#  profiles: test
#  datasource:
#    url: jdbc:tc:postgresql:13-alpine:///FMH_TEST
#    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
#    spring:
#      jpa:
#        database-platform:  org.hibernate.dialect.PostgreSQL9Dialect